# Generated by Django 5.1.7 on 2025-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offerdetails',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_type',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='standard', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='detail titel', max_length=255),
        ),
    ]
