# Generated by Django 5.1.7 on 2025-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_remove_order_offerdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_type',
            field=models.CharField(max_length=50),
        ),
    ]
