# Generated by Django 5.1.7 on 2025-04-26 16:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('file', models.FileField(default='uploads/profiles/default.jpg', upload_to='uploads/profiles/')),
                ('location', models.CharField(default='nicht angegeben', max_length=255)),
                ('tel', models.CharField(default='nicht angegeben', max_length=255)),
                ('description', models.CharField(default='nicht angegeben', max_length=255)),
                ('working_hours', models.CharField(default='nicht angegeben', max_length=255)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='customer', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
